"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const server_1 = require("convex/server");
const values_1 = require("convex/values");
/** Keeps migration Convex deployment aligned with tables written in `migrations.ts`. */
exports.default = (0, server_1.defineSchema)({
    users: (0, server_1.defineTable)({
        ssoUserId: values_1.v.string(),
        wordpressUserId: values_1.v.number(),
        email: values_1.v.string(),
        firstName: values_1.v.string(),
        lastName: values_1.v.string(),
        role: values_1.v.union(values_1.v.literal("user"), values_1.v.literal("admin"), values_1.v.literal("superadmin")),
        onboardingCompleted: values_1.v.boolean(),
        signupSideEffectsCompleted: values_1.v.boolean(),
        createdAt: values_1.v.number(),
        updatedAt: values_1.v.number(),
        activeAccountId: values_1.v.optional(values_1.v.string()),
    }).index("by_ssoUserId", ["ssoUserId"]),
    accounts: (0, server_1.defineTable)({
        ownerId: values_1.v.string(),
        type: values_1.v.string(),
        name: values_1.v.string(),
        slug: values_1.v.string(),
        createdAt: values_1.v.number(),
        updatedAt: values_1.v.number(),
        isDefault: values_1.v.optional(values_1.v.boolean()),
        onboardingCompleted: values_1.v.optional(values_1.v.boolean()),
        isActiveAdvisor: values_1.v.optional(values_1.v.boolean()),
    }).index("by_ownerId_type", ["ownerId", "type"]),
    accountMemberships: (0, server_1.defineTable)({
        accountId: values_1.v.id("accounts"),
        userId: values_1.v.string(),
        role: values_1.v.string(),
        createdAt: values_1.v.number(),
    }),
    accountProfiles: (0, server_1.defineTable)({
        accountId: values_1.v.id("accounts"),
        visibility: values_1.v.union(values_1.v.literal("private"), values_1.v.literal("public")),
        displayUnit: values_1.v.union(values_1.v.literal("Kg"), values_1.v.literal("Lbs"), values_1.v.literal("Bottles")),
        sectionOrder: values_1.v.array(values_1.v.string()),
        ctaUrl: values_1.v.optional(values_1.v.string()),
        inviteUrl: values_1.v.optional(values_1.v.string()),
        wordmarkId: values_1.v.optional(values_1.v.string()),
        logoId: values_1.v.optional(values_1.v.string()),
        createdAt: values_1.v.number(),
        updatedAt: values_1.v.number(),
    }),
    profileSections: (0, server_1.defineTable)({
        accountId: values_1.v.id("accounts"),
        /** Migration writes `{}`; main app may use richer shapes. */
        config: values_1.v.any(),
        createdAt: values_1.v.number(),
        updatedAt: values_1.v.number(),
    }),
    tribes: (0, server_1.defineTable)({
        leaderAccountId: values_1.v.string(),
        type: values_1.v.string(),
        createdAt: values_1.v.number(),
    }),
    referralCodes: (0, server_1.defineTable)({
        accountId: values_1.v.string(),
        code: values_1.v.string(),
        isActive: values_1.v.boolean(),
        createdAt: values_1.v.number(),
        updatedAt: values_1.v.number(),
    }),
    impactRecords: (0, server_1.defineTable)({
        impactId: values_1.v.string(),
        accountId: values_1.v.string(),
        impactAmount: values_1.v.number(),
        impactRegion: values_1.v.string(),
        programId: values_1.v.string(),
        templateId: values_1.v.string(),
        source: values_1.v.string(),
        state: values_1.v.string(),
        attributionStatus: values_1.v.union(values_1.v.literal("assigned"), values_1.v.literal("unclaimed")),
        certificateNameOverride: values_1.v.string(),
        orderId: values_1.v.string(),
        originalEmail: values_1.v.string(),
        purchaserEmail: values_1.v.string(),
        createdAt: values_1.v.number(),
        contributionKind: values_1.v.union(values_1.v.literal("business"), values_1.v.literal("personal"), values_1.v.literal("other")),
    }),
    trials: (0, server_1.defineTable)({
        accountId: values_1.v.string(),
        type: values_1.v.string(),
        startDate: values_1.v.number(),
        endDate: values_1.v.number(),
        source: values_1.v.string(),
        status: values_1.v.union(values_1.v.literal("active"), values_1.v.literal("expired")),
        createdAt: values_1.v.number(),
        updatedAt: values_1.v.number(),
    }),
    calculatorResponses: (0, server_1.defineTable)({
        userId: values_1.v.id("users"),
        accountId: values_1.v.optional(values_1.v.id("accounts")),
        attemptNumber: values_1.v.number(),
        country: values_1.v.optional(values_1.v.object({
            code: values_1.v.string(),
            title: values_1.v.string(),
            averageKg: values_1.v.number(),
        })),
        preferenceId: values_1.v.optional(values_1.v.string()),
        answers: values_1.v.record(values_1.v.string(), values_1.v.string()),
        scoreTotal: values_1.v.optional(values_1.v.number()),
        scoreBase: values_1.v.optional(values_1.v.number()),
        scoreByPage: values_1.v.optional(values_1.v.object({
            q1: values_1.v.number(),
            q2: values_1.v.number(),
            q3: values_1.v.number(),
            q4: values_1.v.number(),
            q5: values_1.v.number(),
        })),
        demographics: values_1.v.optional(values_1.v.object({
            age: values_1.v.optional(values_1.v.string()),
            gender: values_1.v.optional(values_1.v.string()),
            occupation: values_1.v.optional(values_1.v.string()),
        })),
        newsletterOptIn: values_1.v.optional(values_1.v.boolean()),
        sdgPersonal: values_1.v.optional(values_1.v.array(values_1.v.string())),
        sdgPlanet: values_1.v.optional(values_1.v.array(values_1.v.string())),
        referredBy: values_1.v.optional(values_1.v.string()),
        currentPage: values_1.v.string(),
        status: values_1.v.union(values_1.v.literal("in_progress"), values_1.v.literal("completed")),
        completedAt: values_1.v.optional(values_1.v.number()),
        createdAt: values_1.v.number(),
        updatedAt: values_1.v.number(),
    }),
});
